<a href="https://colab.research.google.com/github/rohini-th/Ai/blob/main/Final_project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import nltk
from nltk.tokenize import word_tokenize

from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Input, LSTM, Embedding, Dropout
from tensorflow.keras.callbacks import EarlyStopping

In [2]:

df = pd.read_csv("/content/Reviews.csv", usecols=["Text"])

df = df.head(3000)

df.head()

                                                Text
0  I have bought several of the Vitality canned d...
1  Product arrived labeled as Jumbo Salted Peanut...
2  This is a confection that has been around a fe...
3  If you are looking for the secret ingredient i...
4  Great taffy at a great price.  There was a wid...

In [3]:
import re
def clean_text(text):

    text = str(text).lower()

    text = re.sub(r'[^a-zA-Z ]','',text)

    text = re.sub(r'\s+',' ',text)

    return text

df["Text"] = df["Text"].apply(clean_text)

In [4]:
df = df[df["Text"]!=""]

**Tokenization**

In [5]:
tokenizer = Tokenizer(num_words=5000, oov_token="<OOV>")
tokenizer.fit_on_texts(df["Text"])

total_words = 5000
print(total_words)

5000

In [6]:
print(len(tokenizer.word_index)+1)

12148

In [7]:
wordindex = tokenizer.word_index
reverse_word_index = {index:word for word,index in wordindex.items()}
print(reverse_word_index)

{1: '<OOV>', 2: 'the', 3: 'i', 4: 'and', 5: 'a', 6: 'to', 7: 'of', 8: 'it', 9: 'is', 10: 'this', 11: 'for', 12: 'in', 13: 'my', 14: 'are', 15: 'that', 16: 'but', 17: 'with', 18: 'you', 19: 'not', 20: 'they', 21: 'have', 22: 'was', 23: 'these', 24: 'as', 25: 'br', 26: 'on', 27: 'so', 28: 'like', 29: 'them', 30: 'good', 31: 'chips', 32: 'or', 33: 'be', 34: 'great', 35: 'at', 36: 'just', 37: 'very', 38: 'if', 39: 'all', 40: 'taste', 41: 'flavor', 42: 'its', 43: 'one', 44: 'product', 45: 'we', 46: 'from', 47: 'can', 48: 'love', 49: 'tea', 50: 'had', 51: 'when', 52: 'than', 53: 'will', 54: 'more', 55: 'were', 56: 'me', 57: 'has', 58: 'other', 59: 'food', 60: 'out', 61: 'would', 62: 'really', 63: 'some', 64: 'no', 65: 'only', 66: 'about', 67: 'get', 68: 'too', 69: 'much', 70: 'dont', 71: 'because', 72: 'bag', 73: 'also', 74: 'an', 75: 'your', 76: 'best', 77: 'buy', 78: 'am', 79: 'time', 80: 'better', 81: 'find', 82: 'up', 83: 'coffee', 84: 'use', 85: 'little', 86: 'there', 87: 'amazon', 88: 'which', 89: 'tried', 90: 'by', 91: 'price', 92: 'make', 93: 'do', 94: 'try', 95: 'what', 96: 'even', 97: 'water', 98: 'im', 99: 'flavors', 100: 'ive', 101: 'eat', 102: 'been', 103: 'well', 104: 'any', 105: 'now', 106: 'their', 107: 'sugar', 108: 'our', 109: 'after', 110: 'mix', 111: 'again', 112: 'first', 113: 'bags', 114: 'salt', 115: 'he', 116: 'then', 117: 'she', 118: 'found', 119: 'potato', 120: 'made', 121: 'used', 122: 'bought', 123: 'order', 124: 'box', 125: 'favorite', 126: 'think', 127: 'sweet', 128: 'delicious', 129: 'pack', 130: 'recommend', 131: 'many', 132: 'know', 133: 'could', 134: 'brand', 135: 'go', 136: 'over', 137: 'since', 138: 'still', 139: 'store', 140: 'how', 141: 'drink', 142: 'snack', 143: 'who', 144: 'way', 145: 'most', 146: 'got', 147: 'without', 148: 'bit', 149: 'green', 150: 'add', 151: 'two', 152: 'before', 153: 'dog', 154: 'ever', 155: 'did', 156: 'healthy', 157: 'cant', 158: 'ordered', 159: 'her', 160: 'every', 161: 'say', 162: 'want', 163: 'chocolate', 164: 'give', 165: 'nice', 166: 'kettle', 167: 'ingredients', 168: 'tasty', 169: 'something', 170: 'small', 171: 'never', 172: 'tastes', 173: 'quality', 174: 'didnt', 175: 'easy', 176: 'day', 177: 'fresh', 178: 'lot', 179: 'enough', 180: 'eating', 181: 'same', 182: 'few', 183: 'different', 184: 'less', 185: 'organic', 186: 'coconut', 187: 'makes', 188: 'does', 189: 'hot', 190: 'perfect', 191: 'hard', 192: 'calories', 193: 'always', 194: 'right', 195: 'fat', 196: 'size', 197: 'per', 198: 'years', 199: 'regular', 200: 'enjoy', 201: 'natural', 202: 'free', 203: 'bad', 204: 'whole', 205: 'chip', 206: 'shipping', 207: 'back', 208: 'sure', 209: 'while', 210: 'local', 211: 'oz', 212: 'products', 213: 'however', 214: 'off', 215: 'old', 216: 'each', 217: 'those', 218: 'case', 219: 'into', 220: 'keep', 221: 'stuff', 222: 'loves', 223: 'high', 224: 'being', 225: 'definitely', 226: 'pretty', 227: 'cup', 228: 'long', 229: 'his', 230: 'looking', 231: 'both', 232: 'need', 233: 'though', 234: 'using', 235: 'put', 236: 'brands', 237: 'foods', 238: 'thing', 239: 'vinegar', 240: 'popcorn', 241: 'take', 242: 'doesnt', 243: 'thought', 244: 'milk', 245: 'big', 246: 'strong', 247: 'oil', 248: 'far', 249: 'actually', 250: 'going', 251: 'theyre', 252: 'variety', 253: 'down', 254: 'cream', 255: 'dogs', 256: 'tasted', 257: 'purchased', 258: 'excellent', 259: 'real', 260: 'here', 261: 'cookies', 262: 'new', 263: 'family', 264: 'wonderful', 265: 'highly', 266: 'almost', 267: 'diet', 268: 'white', 269: 'came', 270: 'may', 271: 'grocery', 272: 'happy', 273: 'see', 274: 'away', 275: 'people', 276: 'ones', 277: 'texture', 278: 'loved', 279: 'full', 280: 'buying', 281: 'reviews', 282: 'purchase', 283: 'low', 284: 'having', 285: 'things', 286: 'amount', 287: 'wont', 288: 'spicy', 289: 'powder', 290: 'stores', 291: 'work', 292: 'half', 293: 'year', 294: 'added', 295: 'around', 296: 'worth', 297: 'usually', 298: 'light', 299: 'should', 300: 'anything', 301: 'salty', 302: 'probably', 303: 'money', 304: 'through', 305: 'juice', 306: 'sauce', 307: 'id', 308: 'expensive', 309: 'where', 310: 'calorie', 311: 'thats', 312: 'rice', 313: 'received', 314: 'youre', 315: 'come', 316: 'him', 317: 'said', 318: 'instead', 319: 'item', 320: 'deal', 321: 'us', 322: 'another', 323: 'pepper', 324: 'treat', 325: 'trying', 326: 'comes', 327: 'pineapple', 328: 'baby', 329: 'feel', 330: 'quite', 331: 'tasting', 332: 'cake', 333: 'several', 334: 'husband', 335: 'disappointed', 336: 'popchips', 337: 'arrived', 338: 'weight', 339: 'package', 340: 'last', 341: 'wanted', 342: 'baked', 343: 'fruit', 344: 'open', 345: 'such', 346: 'own', 347: 'especially', 348: 'why', 349: 'drinking', 350: 'corn', 351: 'crunchy', 352: 'others', 353: 'fact', 354: 'friends', 355: 'liked', 356: 'health', 357: 'available', 358: 'might', 359: 'kids', 360: 'once', 361: 'company', 362: 'wish', 363: 'home', 364: 'ordering', 365: 'three', 366: 'nothing', 367: 'cheaper', 368: 'stars', 369: 'kind', 370: 'months', 371: 'isnt', 372: 'black', 373: 'review', 374: 'stevia', 375: 'plus', 376: 'look', 377: 'least', 378: 'seems', 379: 'ago', 380: 'problem', 381: 'serving', 382: 'save', 383: 'plain', 384: 'meal', 385: 'alternative', 386: 'making', 387: 'cans', 388: 'energy', 389: 'snacks', 390: 'maybe', 391: 'large', 392: 'rather', 393: 'pop', 394: 'blend', 395: 'gave', 396: 'absolutely', 397: 'everyone', 398: 'dark', 399: 'ill', 400: 'getting', 401: 'packaging', 402: 'treats', 403: 'dry', 404: 'able', 405: 'days', 406: 'chicken', 407: 'decided', 408: 'soup', 409: 'crunch', 410: 'cats', 411: 'top', 412: 'online', 413: 'flavored', 414: 'started', 415: 'healthier', 416: 'cat', 417: 'bbq', 418: 'candy', 419: 'seem', 420: 'butter', 421: 'waffles', 422: 'waffle', 423: 'oreo', 424: 'times', 425: 'either', 426: 'mouth', 427: 'couple', 428: 'cheese', 429: 'couldnt', 430: 'son', 431: 'everything', 432: 'read', 433: 'says', 434: 'bitter', 435: 'market', 436: 'tomatoes', 437: 'pancake', 438: 'pancakes', 439: 'believe', 440: 'gift', 441: 'else', 442: 'until', 443: 'extra', 444: 'bottle', 445: 'syrup', 446: 'brown', 447: 'side', 448: 'went', 449: 'original', 450: 'must', 451: 'sour', 452: 'next', 453: 'let', 454: 'teas', 455: 'iced', 456: 'amazing', 457: 'ok', 458: 'although', 459: 'ginger', 460: 'sea', 461: 'potatoes', 462: 'sodium', 463: 'cut', 464: 'likes', 465: 'glad', 466: 'boxes', 467: 'cereal', 468: 'quick', 469: 'ounce', 470: 'fast', 471: 'morning', 472: 'raw', 473: 'took', 474: 'prefer', 475: 'month', 476: 'formula', 477: 'red', 478: 'fan', 479: 'single', 480: 'fine', 481: 'wasnt', 482: 'thank', 483: 'looked', 484: 'slightly', 485: 'smell', 486: 'vanilla', 487: 'super', 488: 'yet', 489: 'works', 490: 'honey', 491: 'peanut', 492: 'anyone', 493: 'longer', 494: 'youll', 495: 'smooth', 496: 'label', 497: 'g', 498: 'plastic', 499: 'weeks', 500: 'protein', 501: 'easily', 502: 'shipped', 503: 'recipe', 504: 'cheddar', 505: 'pasta', 506: 'canned', 507: 'flavorful', 508: 'myself', 509: 'thanks', 510: 'breakfast', 511: 'awesome', 512: 'type', 513: 'bottom', 514: 'havent', 515: 'cold', 516: 'ate', 517: 'idea', 518: 'recently', 519: 'part', 520: 'mixed', 521: 'smaller', 522: 'packets', 523: 'crackers', 524: 'pieces', 525: 'version', 526: 'daughter', 527: 'drinks', 528: 'rich', 529: 'garlic', 530: 'choice', 531: 'along', 532: 'beans', 533: 'line', 534: 'wrong', 535: 'reason', 536: 'packaged', 537: 'meat', 538: 'week', 539: 'color', 540: 'minutes', 541: 'eaten', 542: 'second', 543: 'goes', 544: 'opened', 545: 'pleased', 546: 'house', 547: 'unfortunately', 548: 'cinnamon', 549: 'packs', 550: 'cost', 551: 'cookie', 552: 'needed', 553: 'licorice', 554: 'recommended', 555: 'often', 556: 'instant', 557: 'oatmeal', 558: 'cook', 559: 'course', 560: 'problems', 561: 'ice', 562: 'hand', 563: 'noodles', 564: 'rest', 565: 'cooked', 566: 'greasy', 567: 'certified', 568: 'etc', 569: 'place', 570: 'spice', 571: 'arent', 572: 'inside', 573: 'thin', 574: 'care', 575: 'artificial', 576: 'fiber', 577: 'experience', 578: 'items', 579: 'soon', 580: 'value', 581: 'onion', 582: 'list', 583: 'egg', 584: 'thai', 585: 'tiny', 586: 'yummy', 587: 'service', 588: 'similar', 589: 'wouldnt', 590: 'christmas', 591: 'lunch', 592: 'broken', 593: 'starbucks', 594: 'soy', 595: 'chowder', 596: 'nuts', 597: 'sometimes', 598: 'help', 599: 'left', 600: 'crisp', 601: 'feed', 602: 'larger', 603: 'flour', 604: 'overall', 605: 'ingredient', 606: 'enjoyed', 607: 'cannot', 608: 'given', 609: 'normal', 610: 'farms', 611: 'subscribe', 612: 'baking', 613: 'contains', 614: 'expected', 615: 'bold', 616: 'gets', 617: 'aftertaste', 618: 'balance', 619: 'told', 620: 'life', 621: 'gluten', 622: 'lots', 623: 'calcium', 624: 'looks', 625: 'delivery', 626: 'pound', 627: 'between', 628: 'higher', 629: 'cheap', 630: 'end', 631: 'during', 632: 'please', 633: 'theres', 634: 'change', 635: 'live', 636: 'surprised', 637: 'gives', 638: 'carry', 639: 'four', 640: 'yourself', 641: 'potassium', 642: 'cherry', 643: 'soft', 644: 'itbr', 645: 'noticed', 646: 'past', 647: 'exactly', 648: 'someone', 649: 'convenient', 650: 'thick', 651: 'tell', 652: 'packet', 653: 'stick', 654: 'hope', 655: 'fantastic', 656: 'clean', 657: 'pay', 658: 'special', 659: 'bar', 660: 'french', 661: 'expect', 662: 'certainly', 663: 'mg', 664: 'loose', 665: 'name', 666: 'delivered', 667: 'bowl', 668: 'stash', 669: 'done', 670: 'hint', 671: 'dinner', 672: 'purchasing', 673: 'summer', 674: 'fun', 675: 'cooking', 676: 'finally', 677: 'stop', 678: 'truly', 679: 'unless', 680: 'wheat', 681: 'difficult', 682: 'simply', 683: 'plan', 684: 'guess', 685: 'varieties', 686: 'difference', 687: 'sweetener', 688: 'due', 689: 'cups', 690: 'discovered', 691: 'helps', 692: 'sale', 693: 'container', 694: 'called', 695: 'twice', 696: 'portion', 697: 'star', 698: 'clam', 699: 'feeding', 700: 'stale', 701: 'shipment', 702: 'roast', 703: 'whatever', 704: 'filling', 705: 'saw', 706: 'bland', 707: 'mild', 708: 'bottles', 709: 'mind', 710: 'quickly', 711: 'kcups', 712: 'air', 713: 'vitamin', 714: 'five', 715: 'mostly', 716: 'gourmet', 717: 'takes', 718: 'run', 719: 'content', 720: 'sold', 721: 'crispy', 722: 'entire', 723: 'date', 724: 'mine', 725: 'lays', 726: 'favorites', 727: 'none', 728: 'together', 729: 'unique', 730: 'stay', 731: 'apple', 732: 'stock', 733: 'adding', 734: 'bean', 735: 'glass', 736: 'refreshing', 737: 'lemon', 738: 'mint', 739: 'contain', 740: 'bars', 741: 'extract', 742: 'world', 743: 'heat', 744: 'extremely', 745: 'later', 746: 'fish', 747: 'waste', 748: 'wow', 749: 'yes', 750: 'individual', 751: 'trans', 752: 'hit', 753: 'microwave', 754: 'giving', 755: 'already', 756: 'results', 757: 'gone', 758: 'hate', 759: 'customer', 760: 'throw', 761: 'fried', 762: 'bulk', 763: 'addition', 764: 'packed', 765: 'strawberry', 766: 'six', 767: 'packages', 768: 'weve', 769: 'needs', 770: 'huge', 771: 'count', 772: 'sent', 773: 'source', 774: 'nutrition', 775: 'terrible', 776: 'opinion', 777: 'jar', 778: 'start', 779: 'control', 780: 'seen', 781: 'description', 782: 'daily', 783: 'leaves', 784: 'salad', 785: 'ground', 786: 'beat', 787: 'mountain', 788: 'soda', 789: 'party', 790: 'eats', 791: 'combination', 792: 'mean', 793: 'remember', 794: 'watchers', 795: 'sweetness', 796: 'become', 797: 'close', 798: 'friend', 799: 'kick', 800: 'website', 801: 'consistency', 802: 'prime', 803: 'crazy', 804: 'kitchen', 805: 'coffees', 806: 'sort', 807: 'point', 808: 'based', 809: 'olive', 810: 'compared', 811: 'excited', 812: 'true', 813: 'total', 814: 'frosting', 815: 'pounds', 816: 'reasonable', 817: 'wife', 818: 'salsa', 819: 'roasted', 820: 'option', 821: 'expecting', 822: 'amazoncom', 823: 'easier', 824: 'dried', 825: 'caffeine', 826: 'eggs', 827: 'dish', 828: 'nearly', 829: 'locally', 830: 'mess', 831: 'today', 832: 'pods', 833: 'seemed', 834: 'nutritional', 835: 'mixes', 836: 'sell', 837: 'shop', 838: 'form', 839: 'keeps', 840: 'somewhat', 841: 'popper', 842: 'issue', 843: 'lb', 844: 'bite', 845: 'forward', 846: 'immediately', 847: 'clear', 848: 'anymore', 849: 'acid', 850: 'recipes', 851: 'fair', 852: 'itself', 853: 'continue', 854: 'means', 855: 'hooked', 856: 'leave', 857: 'liquid', 858: 'herbs', 859: 'completely', 860: 'serve', 861: 'china', 862: 'msg', 863: 'splash', 864: 'popped', 865: 'cacao', 866: 'dop', 867: 'totally', 868: 'impressed', 869: 'gum', 870: 'share', 871: 'lbs', 872: 'changed', 873: 'vet', 874: 'stomach', 875: 'oh', 876: 'decent', 877: 'pure', 878: 'grams', 879: 'veggies', 880: 'nasty', 881: 'knew', 882: 'kernels', 883: 'stuck', 884: 'served', 885: 'picked', 886: 'under', 887: 'person', 888: 'outside', 889: 'unlike', 890: 'okay', 891: 'flavoring', 892: 'pet', 893: 'picky', 894: 'dip', 895: 'heard', 896: 'seasoning', 897: 'condition', 898: 'within', 899: 'ounces', 900: 'training', 901: 'school', 902: 'perfectly', 903: 'doing', 904: 'otherwise', 905: 'basically', 906: 'seeds', 907: 'satisfying', 908: 'seller', 909: 'science', 910: 'heavy', 911: 'awful', 912: 'perhaps', 913: 'vegetable', 914: 'paid', 915: 'overpowering', 916: 'except', 917: 'including', 918: 'brew', 919: 'mini', 920: 'bits', 921: 'reading', 922: 'decaf', 923: 'pod', 924: 'kcup', 925: 'fluffy', 926: 'oreos', 927: 'tangy', 928: 'substitute', 929: 'subscription', 930: 'rose', 931: 'earths', 932: 'maker', 933: 'harmony', 934: 'nabisco', 935: 'peanuts', 936: 'office', 937: 'gold', 938: 'carb', 939: 'short', 940: 'reviewer', 941: 'cause', 942: 'issues', 943: 'hes', 944: 'themselves', 945: 'servings', 946: 'wait', 947: 'weak', 948: 'keurig', 949: 'caribou', 950: 'fats', 951: 'yogurt', 952: 'lightly', 953: 'points', 954: 'coco', 955: 'mahogany', 956: 'powdered', 957: 'fridge', 958: 'craving', 959: 'finding', 960: 'actual', 961: 'tired', 962: 'personally', 963: 'body', 964: 'overly', 965: 'middle', 966: 'set', 967: 'bigger', 968: 'frozen', 969: 'felt', 970: 'ship', 971: 'benefits', 972: 'note', 973: 'addicted', 974: 'hoping', 975: 'filled', 976: 'lower', 977: 'restaurant', 978: 'vegetables', 979: 'call', 980: 'wants', 981: 'nicely', 982: 'c', 983: 'site', 984: 'san', 985: 'pocky', 986: 'lollipops', 987: 'processed', 988: 'beer', 989: 'brought', 990: 'watch', 991: 'prepare', 992: 'cane', 993: 'maple', 994: 'pot', 995: 'spices', 996: 'aroma', 997: 'agree', 998: 'switched', 999: 'anyway', 1000: 'simple', 1001: 'tart', 1002: 'horrible', 1003: 'finish', 1004: 'wine', 1005: 'jalapeno', 1006: 'flavorbr', 1007: 'suggest', 1008: 'japanese', 1009: 'aware', 1010: 'stonewall', 1011: 'wrapped', 1012: 'anywhere', 1013: 'minute', 1014: 'convenience', 1015: 'chance', 1016: 'ready', 1017: 'consider', 1018: 'supermarket', 1019: 'melted', 1020: 'warm', 1021: 'main', 1022: 'allergic', 1023: 'sensitive', 1024: 'moist', 1025: 'oven', 1026: 'orange', 1027: 'return', 1028: 'taking', 1029: 'bread', 1030: 'style', 1031: 'subtle', 1032: 'sampler', 1033: 'blueberry', 1034: 'weird', 1035: 'costs', 1036: 'considering', 1037: 'allergy', 1038: 'barbeque', 1039: 'quantity', 1040: 'barbecue', 1041: 'future', 1042: 'homemade', 1043: 'gbr', 1044: 'sized', 1045: 'particular', 1046: 'trip', 1047: 'satisfied', 1048: 'became', 1049: 'country', 1050: 'ended', 1051: 'important', 1052: 'medium', 1053: 'iron', 1054: 'babies', 1055: 'deep', 1056: 'area', 1057: 'gas', 1058: 'kept', 1059: 'kinds', 1060: 'cocoa', 1061: 'choices', 1062: 'ask', 1063: 'puppy', 1064: 'worse', 1065: 'usual', 1066: 'teeth', 1067: 'hours', 1068: 'tender', 1069: 'thembr', 1070: 'chew', 1071: 'receive', 1072: 'yum', 1073: 'banana', 1074: 'base', 1075: 'coming', 1076: 'turn', 1077: 'cute', 1078: 'avoid', 1079: 'bunch', 1080: 'almond', 1081: 'paper', 1082: 'sweeteners', 1083: 'turned', 1084: 'cakesters', 1085: 'bacon', 1086: 'information', 1087: 'pops', 1088: 'paste', 1089: 'mrs', 1090: 'clams', 1091: 'door', 1092: 'mccanns', 1093: 'oats', 1094: 'hands', 1095: 'pan', 1096: 'prices', 1097: 'various', 1098: 'stopped', 1099: 'pick', 1100: 'jars', 1101: 'oils', 1102: 'allergies', 1103: 'normally', 1104: 'golden', 1105: 'figured', 1106: 'kibble', 1107: 'beef', 1108: 'switch', 1109: 'car', 1110: 'tomato', 1111: 'shot', 1112: 'k', 1113: 'bring', 1114: 'check', 1115: 'cakes', 1116: 'paying', 1117: 'nut', 1118: 'pricey', 1119: 'fairly', 1120: 'lost', 1121: 'thinking', 1122: 'worst', 1123: 'crisps', 1124: 'compare', 1125: 'picture', 1126: 'seed', 1127: 'straight', 1128: 'sandwich', 1129: 'burnt', 1130: 'meals', 1131: 'mention', 1132: 'agave', 1133: 'chewy', 1134: 'realized', 1135: 'lose', 1136: 's', 1137: 'states', 1138: 'intake', 1139: 'mother', 1140: 'machine', 1141: 'sugars', 1142: 'running', 1143: 'send', 1144: 'plenty', 1145: 'daughters', 1146: 'honestly', 1147: 'night', 1148: 'whats', 1149: 'standard', 1150: 'tend', 1151: 'introduced', 1152: 'biscotti', 1153: 'older', 1154: 'blood', 1155: 'feeling', 1156: 'hold', 1157: 'edible', 1158: 'pudding', 1159: 'chemical', 1160: 'adds', 1161: 'caramel', 1162: 'birthday', 1163: 'number', 1164: 'traditional', 1165: 'following', 1166: 'average', 1167: 'sons', 1168: 'supposed', 1169: 'dented', 1170: 'chipsbr', 1171: 'oily', 1172: 'mustard', 1173: 'yellow', 1174: 'adult', 1175: 'hungry', 1176: 'werent', 1177: 'popping', 1178: 'marzano', 1179: 'vita', 1180: 'complaint', 1181: 'realize', 1182: 'personal', 1183: 'guy', 1184: 'blue', 1185: 'living', 1186: 'amounts', 1187: 'shes', 1188: 'helped', 1189: 'creamy', 1190: 'sitting', 1191: 'apart', 1192: 'advertised', 1193: 'trick', 1194: 'target', 1195: 'whenever', 1196: 'loaded', 1197: 'melt', 1198: 'mentioned', 1199: 'types', 1200: 'surprise', 1201: 'grain', 1202: 'despite', 1203: 'shown', 1204: 'coat', 1205: 'offered', 1206: 'walmart', 1207: 'known', 1208: 'children', 1209: 'reduced', 1210: 'matter', 1211: 'break', 1212: 'expiration', 1213: 'job', 1214: 'pleasant', 1215: 'basil', 1216: 'seriously', 1217: 'forget', 1218: 'icing', 1219: 'admit', 1220: 'muffin', 1221: 'youd', 1222: 'chemicals', 1223: 'early', 1224: 'afternoon', 1225: 'bodied', 1226: 'enjoying', 1227: 'omaha', 1228: 'andor', 1229: 'upon', 1230: 'missing', 1231: 'donut', 1232: 'ketchup', 1233: 'double', 1234: 'cases', 1235: 'included', 1236: 'cholesterol', 1237: 'priced', 1238: 'tablespoon', 1239: 'tassimo', 1240: 'dressing', 1241: 'liver', 1242: 'mays', 1243: 'lobster', 1244: 'harbor', 1245: 'salted', 1246: 'selling', 1247: 'candies', 1248: 'flavour', 1249: 'watching', 1250: 'miss', 1251: 'elsewhere', 1252: 'snacking', 1253: 'uses', 1254: 'apples', 1255: 'cents', 1256: 'followed', 1257: 'beverage', 1258: 'gatorade', 1259: 'fell', 1260: 'goodness', 1261: 'mixing', 1262: 'worked', 1263: 'pain', 1264: 'preservatives', 1265: 'everyday', 1266: 'recent', 1267: 'junk', 1268: 'fit', 1269: 'careful', 1270: 'fall', 1271: 'classic', 1272: 'overwhelming', 1273: 'dollars', 1274: 'clearly', 1275: 'putting', 1276: 'instructions', 1277: 'include', 1278: 'nor', 1279: 'rate', 1280: 'asian', 1281: 'mill', 1282: 'belgian', 1283: 'choose', 1284: 'american', 1285: 'generally', 1286: 'lunches', 1287: 'originally', 1288: 'mebr', 1289: 'leaf', 1290: 'safe', 1291: 'gingerbread', 1292: 'wafer', 1293: 'pizza', 1294: 'vendor', 1295: 'lover', 1296: 'shape', 1297: 'allbr', 1298: 'productbr', 1299: 'folks', 1300: 'understand', 1301: 'terrific', 1302: 'hour', 1303: 'chocolates', 1304: 'third', 1305: 'electrolytes', 1306: 'across', 1307: 'concerned', 1308: 'beware', 1309: 'opening', 1310: 'test', 1311: 'mom', 1312: 'multiple', 1313: 'possible', 1314: 'fed', 1315: 'beautiful', 1316: 'premium', 1317: 'pomegranate', 1318: 'molasses', 1319: 'dessert', 1320: 'packing', 1321: 'alive', 1322: 'fill', 1323: 'purse', 1324: 'desk', 1325: 'common', 1326: 'herbal', 1327: 'particularly', 1328: 'cracker', 1329: 'companies', 1330: 'teabr', 1331: 'sample', 1332: 'disappointing', 1333: 'listed', 1334: 'stand', 1335: 'soups', 1336: 'sealed', 1337: 'dirty', 1338: 'england', 1339: 'eater', 1340: 'carrot', 1341: 'pleasantly', 1342: 'levels', 1343: 'tortilla', 1344: 'turkey', 1345: 'saying', 1346: 'child', 1347: 'funny', 1348: 'threw', 1349: 'nd', 1350: 'nustevia', 1351: 'smells', 1352: 'delightful', 1353: 't

**Generate the Input sequences and then apply pad sequences**

In [8]:
df[:10]

                                                Text
0  i have bought several of the vitality canned d...
1  product arrived labeled as jumbo salted peanut...
2  this is a confection that has been around a fe...
3  if you are looking for the secret ingredient i...
4  great taffy at a great price there was a wide ...
5  i got a wild hair for taffy and ordered this f...
6  this saltwater taffy had great flavors and was...
7  this taffy is so good it is very soft and chew...
8  right now im mostly just sprouting this so my ...
9  this is a very healthy dog food good for their...

In [9]:
input_sequences=[]

for line in df["Text"]:

    token_list = tokenizer.texts_to_sequences([line])[0]

    for i in range(1,len(token_list)):

        n_gram_sequence = token_list[:i+1]

        input_sequences.append(n_gram_sequence)
print(input_sequences[:5])

[[3, 21], [3, 21, 122], [3, 21, 122, 333], [3, 21, 122, 333, 7], [3, 21, 122, 333, 7, 2]]

**Paddingt**

In [10]:
MAX_LEN = 30

input_sequences = pad_sequences(
    input_sequences,
    maxlen=MAX_LEN,
    padding='pre',
    truncating='pre'
)

In [11]:
X = input_sequences[:, :-1]
y = input_sequences[:, -1].astype("int32")
print(y.shape)

(220096,)

In [12]:
model = Sequential()

model.add(
    Embedding(
        input_dim=total_words,
        output_dim=64
    )
)

model.add(LSTM(64))
model.add(Dense(total_words, activation="softmax"))

In [13]:
model.compile(
    optimizer="adam",
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"]
)

In [14]:
import tensorflow as tf

print("Total Words:", total_words)

model.summary()

print("X dtype:", X.dtype)
print("y dtype:", y.dtype)

print("GPU:", tf.config.list_physical_devices('GPU'))

Total Words: 5000

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

X dtype: int32
y dtype: int32
GPU: [PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [28]:
X_small = X[:50000]
y_small = y[:50000]

from tensorflow.keras.callbacks import EarlyStopping

early_stop = EarlyStopping(
    monitor="loss",
    patience=3,
    restore_best_weights=True
)

history = model.fit(
    X_small,
    y_small,
    epochs=20,
    batch_size=32,
    callbacks=[early_stop],
    validation_split=0.1
)

Epoch 1/20
1407/1407 ━━━━━━━━━━━━━━━━━━━━ 12s 8ms/step - accuracy: 0.4348 - loss: 2.6443 - val_accuracy: 0.4140 - val_loss: 2.7220
Epoch 2/20
1407/1407 ━━━━━━━━━━━━━━━━━━━━ 11s 8ms/step - accuracy: 0.4547 - loss: 2.5388 - val_accuracy: 0.3830 - val_loss: 2.8547
Epoch 3/20
1407/1407 ━━━━━━━━━━━━━━━━━━━━ 11s 8ms/step - accuracy: 0.4722 - loss: 2.4532 - val_accuracy: 0.3658 - val_loss: 2.9861
Epoch 4/20
1407/1407 ━━━━━━━━━━━━━━━━━━━━ 11s 8ms/step - accuracy: 0.4887 - loss: 2.3591 - val_accuracy: 0.3400 - val_loss: 3.1129
Epoch 5/20
1407/1407 ━━━━━━━━━━━━━━━━━━━━ 12s 8ms/step - accuracy: 0.5085 - loss: 2.2698 - val_accuracy: 0.3220 - val_loss: 3.2479
Epoch 6/20
1407/1407 ━━━━━━━━━━━━━━━━━━━━ 11s 8ms/step - accuracy: 0.5238 - loss: 2.1849 - val_accuracy: 0.3068 - val_loss: 3.3750
Epoch 7/20
1407/1407 ━━━━━━━━━━━━━━━━━━━━ 12s 8ms/step - accuracy: 0.5390 - loss: 2.1087 - val_accuracy: 0.2914 - val_loss: 3.5133
Epoch 8/20
1407/1407 ━━━━━━━━━━━━━━━━━━━━ 20s 8ms/step - accuracy: 0.5556 - loss: 2.0330 - val_accuracy: 0.2816 - val_loss: 3.6352
Epoch 9/20
1407/1407 ━━━━━━━━━━━━━━━━━━━━ 11s 8ms/step - accuracy: 0.5685 - loss: 1.9662 - val_accuracy: 0.2762 - val_loss: 3.7828
Epoch 10/20
1407/1407 ━━━━━━━━━━━━━━━━━━━━ 10s 7ms/step - accuracy: 0.5832 - loss: 1.9037 - val_accuracy: 0.2638 - val_loss: 3.9039
Epoch 11/20
1407/1407 ━━━━━━━━━━━━━━━━━━━━ 11s 8ms/step - accuracy: 0.5954 - loss: 1.8437 - val_accuracy: 0.2608 - val_loss: 4.0352
Epoch 12/20
1407/1407 ━━━━━━━━━━━━━━━━━━━━ 11s 8ms/step - accuracy: 0.6064 - loss: 1.7884 - val_accuracy: 0.2510 - val_loss: 4.1603
Epoch 13/20
1407/1407 ━━━━━━━━━━━━━━━━━━━━ 11s 8ms/step - accuracy: 0.6192 - loss: 1.7352 - val_accuracy: 0.2450 - val_loss: 4.2768
Epoch 14/20
1407/1407 ━━━━━━━━━━━━━━━━━━━━ 12s 8ms/step - accuracy: 0.6292 - loss: 1.6857 - val_accuracy: 0.2374 - val_loss: 4.3991
Epoch 15/20
1407/1407 ━━━━━━━━━━━━━━━━━━━━ 11s 8ms/step - accuracy: 0.6394 - loss: 1.6393 - val_accuracy: 0.2400 - val_loss: 4.5016
Epoch 16/20
1407/1407 ━━━━━━━━━━━━━━━━━━━━ 11s 8ms/step - accuracy: 0.6501 - loss: 1.5948 - val_accuracy: 0.2336 - val_loss: 4.6108
Epoch 17/20
1407/1407 ━━━━━━━━━━━━━━━━━━━━ 11s 8ms/step - accuracy: 0.6560 - loss: 1.5509 - val_accuracy: 0.2326 - val_loss: 4.7039
Epoch 18/20
1407/1407 ━━━━━━━━━━━━━━━━━━━━ 21s 8ms/step - accuracy: 0.6673 - loss: 1.5092 - val_accuracy: 0.2286 - val_loss: 4.8012
Epoch 19/20
1407/1407 ━━━━━━━━━━━━━━━━━━━━ 12s 8ms/step - accuracy: 0.6735 - loss: 1.4772 - val_accuracy: 0.2204 - val_loss: 4.8851
Epoch 20/20
1407/1407 ━━━━━━━━━━━━━━━━━━━━ 11s 8ms/step - accuracy: 0.6827 - loss: 1.4374 - val_accuracy: 0.2172 - val_loss: 4.9770

In [26]:

def generate_text(seed_text, next_words):

    for _ in range(next_words):

        token_list = tokenizer.texts_to_sequences([seed_text])[0]

        token_list = pad_sequences(
            [token_list],
            maxlen=MAX_LEN - 1,
            padding='pre',
            truncating='pre'
        )

        preds = model.predict(token_list, verbose=0)[0]
        temperature = 0.8
        preds = np.log(preds + 1e-10) / temperature
        preds = np.exp(preds)
        preds = preds / np.sum(preds)
        predicted = np.random.choice(len(preds), p=preds)
        output_word = tokenizer.index_word.get(predicted, "")

        # Stop if no word is found
        if output_word == "":
            break

        seed_text += " " + output_word

    return seed_text

In [27]:
print(generate_text("this food",20))

print(generate_text("i love",50))

print(generate_text("the taste",20))

this food was fast and simply almost buy weight carries this product again and different food the sugar version my family loves
i love this for my year of my pet food i use this product again but we bought this order i tried it in the flavors wow i will reorder with the past years they are the best i like ever eaten they are not wonderfully crunchy and the only thing were
the taste of light and crispy extremely nice tasty well crunchy chips i love them they are not too too rich or